import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "#855300",
        "primary-container": "#f59e0b",
        "on-primary": "#ffffff",
        "on-primary-container": "#613b00",
        "primary-fixed": "#ffddb8",
        "primary-fixed-dim": "#ffb95f",
        "inverse-primary": "#ffb95f",
        secondary: "#77574d",
        "secondary-container": "#fed3c7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795950",
        tertiary: "#75584d",
        "tertiary-container": "#cda99d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#573e34",
        surface: "#fbf9f5",
        "surface-variant": "#e4e2de",
        "surface-tint": "#855300",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#534434",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        outline: "#867461",
        "outline-variant": "#d8c3ad",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
